//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsignalr.Models.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiThi
    {
        public int Id { get; set; }
        public Nullable<int> Id_DeThi { get; set; }
        public string DapAn { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<int> Id_DM_KhoaHoc { get; set; }
        public Nullable<int> IdNhanVien { get; set; }
        public Nullable<int> IdLanThi { get; set; }
    }
}
