//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsignalr.Models.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTaiLieu
    {
        public int Id { get; set; }
        public Nullable<int> IdLoaiTaiLieu { get; set; }
        public Nullable<int> IdNhanVien { get; set; }
        public string DuongDan { get; set; }
        public string LoaiFile { get; set; }
    }
}
