//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsignalr.Models.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChungChiNhanVienNgoai
    {
        public int Id { get; set; }
        public Nullable<int> IdNhanVien { get; set; }
        public Nullable<int> IdChungChi { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<int> IdKhoaHoc { get; set; }
    }
}
