//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsignalr.Models.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DapAn
    {
        public int AnswerId { get; set; }
        public Nullable<int> IdCauHoi { get; set; }
        public string TraLoi { get; set; }
        public string DuongDan { get; set; }
        public Nullable<bool> DapAnDung { get; set; }
    
        public virtual NganHangCauHoi NganHangCauHoi { get; set; }
    }
}
