//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsignalr.Models.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeThi
    {
        public int Id { get; set; }
        public string CauHoi { get; set; }
        public string DuongDan { get; set; }
        public Nullable<int> IdMucDo { get; set; }
        public Nullable<int> IdNganHangCauHoi { get; set; }
        public string TraLoiA { get; set; }
        public string TraLoiB { get; set; }
        public string TraLoiC { get; set; }
        public string TraLoiD { get; set; }
        public string TraLoiE { get; set; }
        public string DapAn { get; set; }
        public Nullable<int> Id_DM_KhoaHoc { get; set; }
    }
}
