//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsignalr.Models.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoTrinhDaoTao
    {
        public int Id { get; set; }
        public Nullable<int> MenuId { get; set; }
        public string TenTaiLieu { get; set; }
        public Nullable<int> LanBanHanh { get; set; }
        public Nullable<System.DateTime> NgayBanHanh { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> LinkId { get; set; }
        public string Path { get; set; }
        public string MoTa { get; set; }
        public string FileType { get; set; }
    }
}
