//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsignalr.Models.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiHopDong
    {
        public int Id { get; set; }
        public string TenLoaiHopDong { get; set; }
        public Nullable<int> ThoiHan { get; set; }
        public Nullable<int> Stt { get; set; }
    }
}
