//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsignalr.Models.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiPhuThuoc
    {
        public int Id { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<int> IdQuanHe { get; set; }
        public string MST { get; set; }
        public string QuocTich { get; set; }
        public string CCCD { get; set; }
        public string So_GKS { get; set; }
        public string QuyenSo_GKS { get; set; }
        public string Tinh_GKS { get; set; }
        public string Huyen_GKS { get; set; }
        public string Xa_GKS { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
    }
}
