//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsignalr.Models.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int Id { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string DiaChiThuongTru { get; set; }
        public string QueQuan { get; set; }
        public Nullable<bool> HonNhan { get; set; }
        public Nullable<System.DateTime> NgayVaoCongTy { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgayVaoDang { get; set; }
        public string MaNhanVien { get; set; }
        public string CCCD { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string NoiCap { get; set; }
        public string NoiSinh { get; set; }
        public Nullable<int> IdCongTy { get; set; }
        public Nullable<int> IdPhongBan { get; set; }
        public Nullable<int> IdChucVu { get; set; }
        public Nullable<System.DateTime> NgayNghiViec { get; set; }
    }
}
