//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsignalr.Models.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuaTrinhThi
    {
        public int Id { get; set; }
        public Nullable<int> Id_DM_KhoaHoc { get; set; }
        public Nullable<int> Id_lanThi { get; set; }
        public Nullable<int> IdNhanVien { get; set; }
        public Nullable<System.DateTime> BatDauLuc { get; set; }
        public Nullable<System.DateTime> KetThucLuc { get; set; }
        public Nullable<int> Diem { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<bool> DaLuuChungChi { get; set; }
        public Nullable<System.DateTime> ThoiGianLuu { get; set; }
    }
}
