//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsignalr.Models.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCauThi
    {
        public int Id { get; set; }
        public Nullable<int> Id_DM_KhoaHoc { get; set; }
        public Nullable<int> ThoiGianThi { get; set; }
        public Nullable<int> IdHinhThucThi { get; set; }
        public Nullable<int> SoLuongDapAnDung { get; set; }
        public Nullable<int> SoLuongCauHoi { get; set; }
    }
}
